### ISSUE TITLE
Not possible to save Needle Length Stem value other than integer

### ISSUE THREAD

**Issue by mrmaximas** [briangann/grafana-gauge-panel#102]
Subj

**Comment by mrmaximas** [comment]
@briangann please pay attention

**Comment by briangann** [comment]
sorry for the delay, i'll update it to allow a float value vs integer only,.

**Comment by mrmaximas** [comment]
@briangann thanks!

**Comment by mrmaximas** [comment]
@briangann hi! have any news? thanks!

**Comment by mrmaximas** [comment]
@briangann please don't forget about me ;) Thanks!
