### ISSUE TITLE
Gauge is aligned to the left instead of center

### ISSUE THREAD

**Issue by agaon** [briangann/grafana-gauge-panel#11]
The gauge isn't aligned to the center of the box (like the singlestat gauge) but aligned to the left. This is making dashboard that have both type of gauges look funny...

![image](https://cloud.githubusercontent.com/assets/12067107/22755725/65cb95aa-ee12-11e6-9e7a-18fd402e8cda.png)

**Comment by briangann** [comment]
Definitely a bug, it should be centering by default.

Adding custom margins would probably help to make it center left/right top/bottom as desired.

**Comment by chipper110** [comment]
I am having the same issue, gauge cannot be centered.

**Comment by briangann** [comment]
v0.0.3 fixes this problem, it's all centered properly and accounts for the title as well.

**Comment by chipper110** [comment]
I Have installed v0.0.3 and the gauges are still off center.  
![image](https://cloud.githubusercontent.com/assets/20861450/23948002/7cfed1aa-0957-11e7-92ba-dfa16ae1b3d2.png)

**Comment by briangann** [comment]
did you create a new panel? it may have old settings if not.  I'll double check on a new install to try to reproduce.

**Comment by chipper110** [comment]
Yes, I create a new dashboard.

**Comment by conkrete** [comment]
I also see Gauges aligned to left:  
![image](https://cloud.githubusercontent.com/assets/24722684/24302522/c5c42432-1067-11e7-9564-f0d45e8d60dc.png)

I also always see 2 gauges when created a new Gauge panel

**Comment by briangann** [comment]
looks like the PR didn't reference the right md5 - i'll get it fixed. If you clone the repo into your grafana installation it'll work as expected.  Meanwhile I'll get it updated so it can be install via grafana-cli

**Comment by jeanduporte** [comment]
I have the same problem, the gauge is aligned to the left. Any solution? I have actually the last version (v0.0.3). I have also the problem with the 2 gauges when duplicate but it fixes when you click on update in the json file.
![1](https://user-images.githubusercontent.com/28293036/28915558-cd3c65cc-783f-11e7-8006-c51337a46be6.png)

**Comment by briangann** [comment]
try v0.0.4, it will have the alignment fix inside and let me know if you still see problems.  They're looking correct on my tests.

**Comment by jeanduporte** [comment]
Thanks for answering, we have to wait to update the panel for the moment. I will tell you when it will be updated for us and if the centering is effective.

**Comment by jeanduporte** [comment]
Hi,

After a long time we finally update the panel. The problem with the centering is fixed but there is another one : it doesn't centering on the vetical axe...

![1](https://user-images.githubusercontent.com/28293036/37022604-bb657cfc-2123-11e8-9151-685db6e98dad.png)

**Comment by briangann** [comment]
Confirmed - the vertical axis is bugged now.  Will have a fix for it shortly.

**Comment by briangann** [comment]
latest release fixes the vertical axis alignment, thanks!

**Comment by jeanduporte** [comment]
The bug is back in Grafana 5:
![image](https://user-images.githubusercontent.com/28293036/52063170-5b504f00-2572-11e9-9d99-dce367fafd5b.png)
Anyone has the same problem?
