### ISSUE TITLE
Multiple Gauge via query

### ISSUE THREAD

**Issue by Nayar** [briangann/grafana-gauge-panel#12]
![spectacle j23750](https://cloud.githubusercontent.com/assets/454815/23202764/fa16bbc2-f8f8-11e6-95cc-58a3970e2942.png)

It would be great it the plugin could create multiple gauges by aggregation. e.g, a gauge for each IP in the field `source`

**Comment by briangann** [comment]
I'll take a look at implementing this - alignment/spacing options will be needed to support it at minimum.  Auto-generating multiple gauges would be nice.

**Comment by briangann** [comment]
This is still on the radar - I'd like to have this too.

**Comment by davidpablocohn** [comment]
Would like to second a request for this. Thank you, first of all for the 360 degree gauge;  for all of Grafana's power, I was astounded that it didn't have this. On our ship, we need 360 degree gauges everywhere - course, heading, winds. But it would be great to get multi-gauges, so we could save screen real estate. e.g. overlapping course/heading in one dial, port/starboard winds in another.

For example:

![Capture](https://user-images.githubusercontent.com/22936302/89542012-f3587580-d7b3-11ea-8e91-1171d19a9f5b.PNG)
