### ISSUE TITLE
Cannot add D3 gauge to panel

### ISSUE THREAD

**Issue by kampfflunder** [briangann/grafana-gauge-panel#17]
Hi,
I've installed the plugin successfully and it shows up in Grafana's plugin section.
However, when I try to add 3D Gauge to a new or existing panel, there is only the standard graph option available.
Grafana 4.1.2 on Raspian

I know, you only mention 3.x, but in #6 4.x is also covered.

**Comment by briangann** [comment]
Did you restart the grafana-server process? I think that's required for new plugins to be recognized. If not, I'd check the logs and see if there's an error.  Also, look in /var/lib/grafana/plugins and make sure it is really in there, and permissions/ownership are correct.

**Comment by kampfflunder** [comment]
I was really sure that I restarted grafana-server at least two times, but now I think I was wrong.
Because I can add gauges now :-)
Sorry for the noise,

Rainer

**Comment by dineshkumar4728** [comment]
hi @kampfflunder ,
                        I am intsall the 3D Gauge to grfana.and also i am check the /var/lib/plugins and it is there and i restart the grafana couple of times but still i am unable to find the plugin in grfana UI. can you please help on this ?
Thanks

**Comment by briangann** [comment]
Which method did you use to install it?

With the grafana-cli it should download and install correctly. If you cloned from this repo, I'd check ownership of the path (and everything under it) in /var/lib/grafana/plugins/briangann-gauge-panel

Also look at the startup logs for grafana and see if it is complaining about the plugin.

I'm running it on v5.2.1 also.

```
grafana-cli plugins install briangann-gauge-panel
```

**Comment by aasrp** [comment]
Hi @briangann,
I do not know why, but my needle does not move as values change.
Am I forgetting to set something up?

Tks
![screenshot from 2019-01-16 07-42-11](https://user-images.githubusercontent.com/46744588/51240367-a9eece00-1962-11e9-9916-0deaba47b13d.png)
