### ISSUE TITLE
If Limits min is more than max, crashes browser tab (Chrome)

### ISSUE THREAD

**Issue by chrisbrookes** [briangann/grafana-gauge-panel#18]
Wanted to move both min and max limits up, so tried to change the min first and this happened to be above the current max.
![image](https://cloud.githubusercontent.com/assets/1110134/25905478/0a932192-359a-11e7-8f5e-4c3cabea3629.png)

When I tabbed out of the min entryfield the browser (Chrome 58.0.3029.81 64-bit, Ubuntu 16.04) tab hung then crashed after a second or two.
![image](https://cloud.githubusercontent.com/assets/1110134/25905527/27ab7036-359a-11e7-9702-7b6c2be7d750.png)

Obvious workaround is to increase the max before the min, but it isn't intuitive to do it this way round. When the browser crashes, any changes you were making to your dashboard appear to be lost.

**Comment by dansat** [comment]
I tried as well with safari and chrome, both are crashing the browser if I set minimum > maximum. 

Apart from that (still related with Limit) I noticed if I am using a big metrics and set a huge range, then the numbers are not correctly displayed on the gauge.

Limit min : 79, limit max : 450
![limit_gauge](https://user-images.githubusercontent.com/1125599/27955482-4e766042-6315-11e7-958f-9b1fe099c5a2.png)
Limit min: 79, limit max: 6000
![screen shot 2017-07-07 at 1 11 24 pm](https://user-images.githubusercontent.com/1125599/27955601-def96312-6315-11e7-909e-e241b43539ff.png)

**Comment by dansat** [comment]
I noticed that onRender() there is no check for this.panel.gauge.minValue and this.panel.gauge.maxValue before assigning to opt.minVal, hence on render we have this exception. 

I think a check should be done, and these two values be swapped if min > max (with alertSrvRef and render() recalled on exception). Or are there any use case where this does not go?

**Comment by coolshiva123** [comment]
This happens for me as well

**Comment by briangann** [comment]
confirmed bug - fixing it :)

**Comment by briangann** [comment]
this is fixed in v0.0.4, will be updated on grafana.com soon.

**Comment by briangann** [comment]
v0.0.4 is updated on grafana.com. The fix will auto-adjust min/max +1/-1 as needed and puts up a warning that it is doing so.
