### ISSUE TITLE
Dynamic limits

### ISSUE THREAD

**Issue by Atoms** [briangann/grafana-gauge-panel#2]
As we have service where from time to time limits change it would be good if we could adjust limits dynamically  as change for all panels after change on servers would be hard and forgettable...

My suggestion would be create 2 (or some other count) of metrics, use alias, and then in options select which alias will be limit and which value, 

As limit would be dynamic thresholds also needs to be dynamic (lets say possibility to add upper limit from that alias, and provide previous threshold based on percentiles

**Comment by briangann** [comment]
Sounds like two enhancements:

1) Allow 2 queries to be created, one for the actual value to be displayed, and another for the upper-limit.  There's a lower-limit option also (where the gauge can display values < 0), might need to provide a 3rd query for the lower limit too.

  You could also use a template variable as the source of the upper limit, which may be easier to implement.  Something like $upperLimit, type: query, and use some metric from a datasource for the value. Then you'd plug that $upperLimit into the options.  The same thing can be done for lower-limit

It does sound useful.

2) Thresholds could be handled the same way - dynamic template variables.

Open to PR's if you have any code that does it already :)

**Comment by Atoms** [comment]
I'm not a coder (coding is not my strong side) :) i'm just a user :) so no PR from me :)

**Comment by briangann** [comment]
One more question - is this for Limits under Options, or Thresholding?

**Comment by Atoms** [comment]
Limits under options minimal and maximal.
