### ISSUE TITLE
Threshold Color on Value/Background Not Showing

### ISSUE THREAD

**Issue by deduq** [briangann/grafana-gauge-panel#20]
![d3gaugeissue](https://user-images.githubusercontent.com/11253694/27206628-69379fa6-51ed-11e7-822e-538af7d17b20.PNG)

The value and background don't reflect the thresholds.

Things I've tried:
1. Selecting only one option or both
2. Updating Panel json
3. Scaling threshold value by 1000
4. Cloning the repo (which did fix the centering issue)

Otherwise, enjoying your plugin. Thanks.

**Comment by briangann** [comment]
Checking into this, that shouldn't be happening.

**Comment by briangann** [comment]
The "show threshold color on value" only works on a refresh - that's definitely a bug.
The "show threshold color on background" isn't working at all, I don't think I actually implemented it.

I'll have these fixed soon,

Thanks!

Brian
