### ISSUE TITLE
Add row d3 gauge creates 2 meters in the display

### ISSUE THREAD

**Issue by coolshiva123** [briangann/grafana-gauge-panel#22]
Clicking on add row creates one meter. If i click duplicate, it creates 2 meters some time.
Some times even clicking on new row creates 2 meters.
here is the problem described.

https://community.grafana.com/t/d3-gauge-issue-two-gauge-meters-come/1649

**Comment by briangann** [comment]
The version is wrong on grafana.com plugins, if you clone the repo you will get v1.4, which has the bugfix.

I'll get this updated with Grafana asap. sorry about that.

**Comment by coolshiva123** [comment]
help me to update this in grafana plz..using a git clone ..

**Comment by briangann** [comment]
typically you would:

cd /var/lib/grafana/plugins
git clone https://github.com/briangann/grafana-gauge-panel.git

then restart your grafana server (service grafana-server restart)

**Comment by briangann** [comment]
v0.0.4 is out, and fixes this problem, please update and give it another try.
