### ISSUE TITLE
Alias should also be at metric level

### ISSUE THREAD

**Issue by coolshiva123** [briangann/grafana-gauge-panel#23]
Hi Team,

While using graph panel, it makes sense to have aliases at metric level than query level as script operations are done at metric level and it may be a case where there are certain metrics where no script operation is done but some metrics have scripts (eg arthemetic operation on 2 elastic search fields in a doc). Aliases at query level make no sense here.

PS-May be this is applicable only to elastic search

**Comment by briangann** [comment]
Do you mean the value mappings? It's not clear what you're asking for.
