### ISSUE TITLE
feature wish: max/min indicator on gauge 

### ISSUE THREAD

**Issue by peters77** [briangann/grafana-gauge-panel#24]
Hi, 

great plugin- I used it to display some wheather data grabbed from some sensors into an InfluxDB.

It would be nice to have a max/min indicator to see the maximum and minimum values. 
If it would possible to get a compass rose for displaying wind direction it would be awsome! :-)

Thank you for your great work!

Regards,

Christian

**Comment by briangann** [comment]
Where would you display the min/max values on the gauge? Or do you mean a legend with min/max/current?

**Comment by peters77** [comment]
No, I think it would be great to see the min/max on the gauge like this: 
Maybe two colord single ticks, maybe different colors for min/max:

![bildschirmfoto 2017-08-21 um 07 33 18](https://user-images.githubusercontent.com/8840918/29504940-8b8f6f18-8643-11e7-961b-03f7e7d18137.png)


or even colored between min and max like this:
![bildschirmfoto 2017-08-21 um 07 33 24](https://user-images.githubusercontent.com/8840918/29504949-960f8bb2-8643-11e7-94e0-9d5009717f5d.png)

Hm...a legend tab is another point to think about...?

Regards,

Christian

**Comment by briangann** [comment]
Ah I see, the gauge is showing "current" but would have an option to display the min/max also via markings on the gauge.  Good idea :)

**Comment by peters77** [comment]
Yes. 👍
