### ISSUE TITLE
When data is in the millions the gauge needle doesn't display correctly

### ISSUE THREAD

**Issue by suckamucka** [briangann/grafana-gauge-panel#27]
We are trying to gauge bandwidth from our firewalls in which the firewall reports in bytes. The Gauge shows the value correctly, but the needle is always showing to be at the max.

**Comment by suckamucka** [comment]
![gauge](https://user-images.githubusercontent.com/5890876/31995762-c7c44574-b953-11e7-80db-0a0b85cbfc23.png)
![settings](https://user-images.githubusercontent.com/5890876/31995763-c7cfecd0-b953-11e7-84a8-8ba40fbef805.png)
![readings](https://user-images.githubusercontent.com/5890876/31995764-c7d91e90-b953-11e7-80a3-ca88aabb5efa.png)

**Comment by bmacao** [comment]
Hi, i managed to fix the issue by using "Scale" function in Metrics tab.
In my case to get aprox number i scale(0.9313) and then scale(0.000000001) .
The unit set as "None" ( for current value).

The reason for this bug is that the the needle get the "raw" number and ignores the Unit selected

**Comment by briangann** [comment]
Sounds like a bug, it needs to support the KBN formats on the gauge and when evaluating the raw data, then back to the KBN formatted value for positioning.

**Comment by gannons** [comment]
Noticed this issue is still present. Worked around it by adjust my metric from bytes to MBs. e.g.

> SELECT (mean("bytes") / mean("seconds")) / 1024 / 1024 FROM ......
