### ISSUE TITLE
The G3 CSS overrides other Grafana annotations formatting

### ISSUE THREAD

**Issue by sergeybinfinidat** [briangann/grafana-gauge-panel#37]
Hi, this is my first bug submit in OpenSource project, so if something is missing - please don't get mad
Grafana v4.6.3
D3 Gauge v.0.0.6

The problem is: 
When gauge module appears in the dashboard, any labels inside Grafana annotations become very big.
Caused by CSS overriding the Grafana CSS

See attached screenshots.
![image](https://user-images.githubusercontent.com/6331928/39186173-447a9782-47d2-11e8-92df-99e626698af7.png)
![image](https://user-images.githubusercontent.com/6331928/39186337-c88e9e42-47d2-11e8-9f34-a4dbf6621d40.png)

**Comment by briangann** [comment]
i'll get that fixed right away, thanks!
