### ISSUE TITLE
Error  "_time_series2.default is not a constructor"

### ISSUE THREAD

**Issue by mmallar** [briangann/grafana-gauge-panel#38]
I have been getting the error: " _time_series2.default is not a constructor" when attempting to use the speedometer panel. It had been working since initial install, but has recently (roughly 3 weeks) stopped working. I believe the issue is that something is not being exported as default in the components side of time_series.

**Comment by briangann** [comment]
which version of grafana? i'm using this on grafana 5.3.0 and not seeing errors.

**Comment by mmallar** [comment]
I am no longer with the company that was using this, but will try to get additional info. I know that they are not running the most recent version of grafana.
