### ISSUE TITLE
Thresholding

### ISSUE THREAD

**Issue by arcsyst** [briangann/grafana-gauge-panel#39]
Using thresholding show ranges only works correctly if radial metrics guage degree is 60,60,300,300. Otherwise colouration is misaligned (rotated)

**Comment by m4rky-m4rk** [comment]
Same here

Nice dial. I have been proudly showing it off elsewhere. One thing I did notice is that the the Threshold settings don't work as expected for my dial

![image](https://user-images.githubusercontent.com/26285654/44712163-734a1100-aab0-11e8-9930-c58e38cf9119.png)


Are therplans to allow more style options in the future eg different pointers with arrow head.

Then playing around with the font I could make the gauge more steam punk like.

**Comment by briangann** [comment]
definitely a bug, let me check into this. it is not accounting for the variable degrees

**Comment by rlcomte** [comment]
Any update on this? We see problems with the tresholds in certain situations.
