### ISSUE TITLE
When using more than one dial some settings propagate to the pre-existing dials

### ISSUE THREAD

**Issue by m4rky-m4rk** [briangann/grafana-gauge-panel#41]
Hi,

I had my first dial all nicely set up then I decided to add another dial for a completely different use. This entailed using both value and tick mapping. I noticed that my first dial then also changed its look.  The behaviour wasn't consistent and after a bit of messing around with the settings for both dials I got them to where I wanted. There seemed to be some sort of mix of dial settings. I since tested adding a third dial and it behaved as expected and didn't affect the other dials.

Happened again while playing with thresholds and max, min settings. I couldn't get two dials to be different. The setting for these items on one dial affected the other.

Regards, Mark

**Comment by briangann** [comment]
let me check, i usually have gauges with the same settings, it is possible the saved params are conflicting between different panel instances.

**Comment by dac88** [comment]
Hi @briangann, this bug is a blocker for me. When do you plan to release? Thanks, Dean.

**Comment by briangann** [comment]
will take a look this weekend, the gauges i have on my dashboards are all of the same type, likely why i haven't seen it
