### ISSUE TITLE
Is there a mechanism to add rpm

### ISSUE THREAD

**Issue by flare04** [briangann/grafana-gauge-panel#43]
Where RPM is Revolutions per minute, for fan speeds etc  ?

**Comment by briangann** [comment]
It uses the KBN formats from grafana itself, RPM is under "throughput"

https://github.com/grafana/grafana/blob/b3e6da0cbd5dc1478f51472c1df57eba550af422/public/app/core/utils/kbn.ts

**Comment by flare04** [comment]
OK I was thinking that the units may alter other settings.  I can use reads/min as it only changes the unit shown

**Comment by flare04** [comment]
Forgot to say thanks
