### ISSUE TITLE
Howto install

### ISSUE THREAD

**Issue by pcdiks** [briangann/grafana-gauge-panel#6]
I used the following installation command on my grafana server:
`grafana-cli plugins install briangann-gauge-panel`

Then I restarted grafana with:
`systemctl restart grafana-server.service`

I can then see the new plugin in the list and when I create a new panel. When I want to add the gauge to a new panel I get the following error:
```
Message:

this.gaugeObject is null

Stack trace:

onDataReceived@http://grafana.home.intra:3000/public/plugins/briangann-gauge-panel/ctrl.js?bust=1481321905944:505:13
e.prototype.emit@http://grafana.home.intra:3000/public/app/boot.85c49108.js:48:17521
.execute/d</a.prototype.emit@http://grafana.home.intra:3000/public/app/boot.85c49108.js:48:19604
.execute/i</f.prototype.handleQueryResult@http://grafana.home.intra:3000/public/app/boot.85c49108.js:42:19793
g@http://grafana.home.intra:3000/public/app/boot.85c49108.js:38:29545
h/<@http://grafana.home.intra:3000/public/app/boot.85c49108.js:38:29717
xc/this.$get</o.prototype.$eval@http://grafana.home.intra:3000/public/app/boot.85c49108.js:39:5353
xc/this.$get</o.prototype.$digest@http://grafana.home.intra:3000/public/app/boot.85c49108.js:39:3835
xc/this.$get</o.prototype.$apply@http://grafana.home.intra:3000/public/app/boot.85c49108.js:39:5638
x/i<@http://grafana.home.intra:3000/public/app/boot.85c49108.js:39:1804
f@http://grafana.home.intra:3000/public/app/boot.85c49108.js:37:15602
jb/k.defer/c<@http://grafana.home.intra:3000/public/app/boot.85c49108.js:37:17066
```

Am I missing something or is there something else that needs fixing?

**Comment by briangann** [comment]
What version of Grafana are you using?  I'll try to duplicate the issue - haven't seen it with 3.x/4.x.

**Comment by pcdiks** [comment]
I'm using Grafana server v4.0.2 on Ubuntu 16.04.01. Influxdb is also on this server. Nothing else.

**Comment by briangann** [comment]
ok, i'll stand up a VM like that and see what happens, it's working inside docker for me.

**Comment by briangann** [comment]
I tried this using ubuntu server 16.04.01, and grafana stable: grafana_4.0.2-1481203731_amd64.deb
Installed the plugin, restarted grafana, and the gauge panel drops right into a new row without a problem.  Not sure what is going on with your installation :(

root@ubuntu:~# grafana-cli plugins install briangann-gauge-panel
installing briangann-gauge-panel @ 0.0.1
from url: https://grafana.net/api/plugins/briangann-gauge-panel/versions/0.0.1/download
into: /var/lib/grafana/plugins

✔ Installed briangann-gauge-panel successfully

Restart grafana after installing plugins . <service grafana-server restart>

**Comment by pcdiks** [comment]
I found that I use the gauge only when I create a new dashboard. Adding it to an existing dashboard is not working and then I get the error.
So for now I just create a new dashboard and add the gauge that way.

**Comment by briangann** [comment]
That helped - I was able to reproduce the error. I'll have a fix for it quickly.

Thanks!

**Comment by briangann** [comment]
Fix has been merged, I'll get the panel updated on grafana.net

**Comment by pcdiks** [comment]
Cool, looking forward to that.

**Comment by briangann** [comment]
closing - this bug has been fixed and released.
