### ISSUE TITLE
for dumys but how to install

### ISSUE THREAD

**Issue by syswombat** [briangann/grafana-gauge-panel#62]
Hello
could you tell how to install the Plugin for dumys?
on my Raspberry i have installed yarn with 

apt install yarn

but then 

yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

have a nice day
vinc

**Comment by briangann** [comment]
it's best to install it like this:

```
grafana-cli plugins install briangann-gauge-panel
```

you can also download the zip file and extract it, and move into ` /var/lib/grafana/plugins`
If you want to build it from scratch, see https://github.com/briangann/grafana-gauge-panel#building

```
yarn
yarn build
cp -r dist /var/lib/grafana/plugins/briangann-gauge-panel
```
