### ISSUE TITLE
Gauge name below the value

### ISSUE THREAD

**Issue by m4rky-m4rk** [briangann/grafana-gauge-panel#64]
Hi,

Could an option be added for a gauge name to be included on the dial face below the value. I could then remove the panel title that displays above the guage. This would not only make it look more stylish but save signifiant space thats needed around the gauge.

![image](https://user-images.githubusercontent.com/26285654/111963480-ddee4c80-8af3-11eb-8d0f-9ea0c93741d9.png)

Thanks Mark.

**Comment by briangann** [comment]
that sounds like a good feature, will add it!
