### ISSUE TITLE
Move gauge pointer in "sync" with cursor

### ISSUE THREAD

**Issue by MatinF** [briangann/grafana-gauge-panel#65]
Would it be possible to modify the gauge functionality so that the gauge pointer could be 'synced' with the user cursor?

The idea would be to have a similar functionality as the trackmap-panel plugin, where moving the cursor across a timeseries causes the "dot" to move as well on the map. The aim would be to use this functionality with the gauge to display a "heading" (using a 360 degree gauge) of a vehicle while moving the cursor across a time series.

**Comment by briangann** [comment]
that should be possible, will need to experiment to see how to implement it.

**Comment by MatinF** [comment]
Still hoping to have this added

**Comment by ThamSunc** [comment]
> that should be possible, will need to experiment to see how to implement it.

Hi, Is this applicable already?
Any update, how to figure it out?
