### ISSUE TITLE
Grafana 8 and D3 Gauge

### ISSUE THREAD

**Issue by corsair836** [briangann/grafana-gauge-panel#69]
What happened?
Upgraded to Grafana version 8.0.5 and did global plugin update.  Tried to edit a D3 gauge panel and received an error (attached).

What was expected to happen?
Edit menu should display allowing me to edit the D3 panel.

Steps to reproduce the problem:
1.Update Grafana to version 8.0.5 and do a plugin update (update-all)
2.Access a panel with an existing D3 Gauge panel
3.Click the panel header/menu arrow
4.Grey screen appears with an error message (attached)

Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):
Grafana 8.0.5

Configuration information:
<img width="803" alt="Screen Shot 2021-07-13 at 7 55 45 am" src="https://user-images.githubusercontent.com/8177981/125380877-47150b00-e3d6-11eb-8235-5af27c988669.png">

**Comment by szerwi** [comment]
I had the same issue on 8.0.5, but it seems like Grafana 8.0.6 fixed it.

**Comment by corsair836** [comment]
Nice work @szerwi - 8.0.6 fixed the issue.
