### ISSUE TITLE
Rounding errors on tick labels

### ISSUE THREAD

**Issue by subsven** [briangann/grafana-gauge-panel#7]
Thanks for this great Grafana panel! :)

I currently see two problems using it: The first is the panel disappearing on resize (which is already recorded as #3). The second is a rounding error on the tick labels when using fractional tick spacings.

In the following example I set "Tick Spacing Major" to 0.2 after defining a maximum limit of 1.

![screen shot 2016-12-17 at 19 42 56](https://cloud.githubusercontent.com/assets/599016/21289001/88ed8b7e-c491-11e6-8e28-30b10cfd567d.png)

![screen shot 2016-12-17 at 19 43 02](https://cloud.githubusercontent.com/assets/599016/21289010/ccab2fb0-c491-11e6-878f-07862f653993.png)

Another problem I saw once: my browser window became frozen after I emptied the "Tick Spacing Minor" field.

This is on a current Google Chrome.

**Comment by briangann** [comment]
Working on these bugs now, I did see the same freezing problem once before, will fix that, and check any other fields that may trigger the problem.

Thanks for the feedback!

**Comment by subsven** [comment]
Thanks :-)

**Comment by briangann** [comment]
this was fixed in 0.0.2, forgot to close the bug :)
