### ISSUE TITLE
Plugin not working on Grafana 4.0.1 - Error: this.gaugeObject is null

### ISSUE THREAD

**Issue by kohpinngee** [briangann/grafana-gauge-panel#8]
Error appear on top left corner of plugin with the following stacktrace:

onDataReceived@http://dev.watchmaker.express-scripts.com/public/plugins/briangann-gauge-panel/ctrl.js?bust=1482417960487:505:13
e.prototype.emit@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:48:17332
.execute/d</a.prototype.emit@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:48:19415
.execute/i</f.prototype.handleQueryResult@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:42:19546
g@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:38:29381
h/<@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:38:29553
xc/this.$get</o.prototype.$eval@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:39:5190
xc/this.$get</o.prototype.$digest@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:39:3672
xc/this.$get</o.prototype.$apply@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:39:5475
f/j<@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:39:12931
f@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:37:15442
jb/k.defer/c<@http://dev.watchmaker.express-scripts.com/public/app/boot.fdf40765.js:37:16906

**Comment by briangann** [comment]
The fix for this has been checked in, just need to get the plugin updated on grafana.net.  I'll put in the PR for it now.

Thanks!

**Comment by briangann** [comment]
PR to rev up the plugin has been made: https://github.com/grafana/grafana-plugin-repository/pull/81

**Comment by kohpinngee** [comment]
Thank you.

**Comment by briangann** [comment]
Plugin has been updated on grafana.net, closing this one, on to the others!
