### ISSUE TITLE
Double Gauges appear after Duplicating original one

### ISSUE THREAD

**Issue by fredm1** [briangann/grafana-gauge-panel#9]
After clicking on the "Duplicate", a new panel is added with two gauges. Also occurs if I try to add a second row with the D3 panel. The first time I add the D3 gauge it does display 1 gauge.

![d3_issue](https://cloud.githubusercontent.com/assets/7565549/22349026/c01a9826-e3c2-11e6-9655-4d89b0b53f3b.png)

Grafana Version: 4.0.1
D3 Version: 0.0.2
OS: Amazon Linux 2016.03.3
Browser: Chrome and Firefox

**Comment by briangann** [comment]
I'll check into this - definitely a bug.

**Comment by sbsUlm** [comment]
Same here. By opening the json listing and clicking on update the 2nd gauge disappears.

**Comment by lianghuiyuan** [comment]
+1

**Comment by lmascarenhas** [comment]
" Same here. By opening the json listing and clicking on update the 2nd gauge disappears."
worked for me. =D

**Comment by briangann** [comment]
found and fixed the bug, will be updating with grafana.net shortly. Thanks for the feedback!

**Comment by briangann** [comment]
v0.0.3 fixes this issue and is on grafana.net now

**Comment by fredm1** [comment]
Brian,

Thanks for fixing and for creating the D3 gauge.

Fredm1

**Comment by kentmartin73** [comment]
Hi there,

I've still got this problem with v0.3.  Is there any information or anything I can provide that might help?

<img width="1470" alt="screen shot 2017-04-29 at 13 37 23" src="https://cloud.githubusercontent.com/assets/4977593/25555242/17b1a9f0-2ce1-11e7-999c-8aa58c95f590.png">

**Comment by briangann** [comment]
I just need to update the version with grafana.net - if you "git clone" the panel from this repo you will get the "fixed" version.  the grafana-cli install method pulls the one with the bug currently.

**Comment by kentmartin73** [comment]
Hi Brian,

Nice one - thanks for the update :)

**Comment by briangann** [comment]
v0.0.4 was published correctly this time, the fix is included.  Let me know if you hit any other bugs though :)

**Comment by kentmartin73** [comment]
Cheers, will do :)
